### ISSUE TITLE
How do I compute the joint positions ?

### ISSUE THREAD

**Issue by HaziqRazali** [humans-to-robots-motion/mogaze#1]
Hello. Many thanks for the dataset. I had a look at it but am having an issue trying to understand how I can convert them to global joint coordinates. It is written in the paper that the attributes contain a list of fixed joints, which are only used to scale the urdf to different humans, with a corresponding value.

What does this exactly mean? Why do some joints have a fixed z value whereas some others have a fixed y and z?

Specifically, how can I convert the rot and trans joint data into the global joint coordinates?

**Comment by PhilippJKratzer** [comment]
Hi @HaziqRazali,

Have you been able to run our example notebook: https://github.com/PhilippJKratzer/humoro/blob/master/examples/getting_started.ipynb ?

In the end there is an example for computing joint positions (section Kinematics)

The translational joints are used for scaling. For some of the joints we only have one offset, for example, _lElbowTransX_ specifies the length of the upper arm (offset from shoulder to elbow). Other joints can have offsets in all directions( e.g.  _innerShoulder_ from _torso_). The details are specified in the urdf file (https://github.com/PhilippJKratzer/humoro/blob/master/humoro/data/human.urdf).
