### ISSUE TITLE
Base and Joints orientation representation used

### ISSUE THREAD

**Issue by anish-pratheepkumar** [humans-to-robots-motion/mogaze#2]
Hello, 
Thank you for sharing the dataset.
I was wondering about the representation used for the orientations, could you please let me know if they are in Euler or in Exponential map?

**Comment by PhilippJKratzer** [comment]
Hi @anish-pratheepkumar
The rotations are represented in Euler angles

**Comment by anish-pratheepkumar** [comment]
Thank you so much for your response.

**Comment by jmainpri** [comment]
Should we put which convention is used to represent the rotation?
(Is it specified in the URDF?)

Le mer. 3 févr. 2021 à 17:57, Philipp Kratzer <notifications@github.com> a
écrit :
