### ISSUE TITLE
Difference between 'shoulder' and 'inner shoulder' joint names

### ISSUE THREAD

**Issue by anish-pratheepkumar** [humans-to-robots-motion/mogaze#3]
Hello,

Could you please let me know what is the difference between the joints 'inner shoulder' and 'shoulder'. I could see in the human.urdf that the 'inner shoulder' part doesn't have any geometry defined, I actually wanted to identify what it indicates and its location.

**Comment by PhilippJKratzer** [comment]
Hi,
You can have a look on the middle image (Bone Skeleton) here: https://v22.wiki.optitrack.com/images/thumb/5/57/Assets_ThreeSkeletons.png/800px-Assets_ThreeSkeletons.png
 What we call "innerShoulder" in the human.urdf, is the one before the shoulder ("inner shoulder" -> "shoulder" -> "elbow" -> "wrist"), it can be used to rotate the shoulder.

**Comment by anish-pratheepkumar** [comment]
Perfect! Thank you for your response.
