### ISSUE TITLE
404 error when trying to access the dataset

### ISSUE THREAD

**Issue by Aadi0902** [humans-to-robots-motion/mogaze#4]
Hello,

I was trying to access the mogaze dataset using [this](pkratzer.net/mogaze.zip) link but keep getting a 404 Not found error. Could you please look into it and let me know about an updated link or where I can access the dataset?

**Comment by PhilippJKratzer** [comment]
Hi @Aadi0902,

Thanks for your message. I was moving the website recently. It should be available again (same link pkratzer.net/mogaze.zip).
